### ISSUE TITLE
How to add custom headers for CSRF Token in the form request

### ISSUE THREAD

**Issue by mulky-sulaiman** [gearbox-solutions/nuxt-precognition#1]
Greetings,

I previously working on app using VILT stack, and now I'm trying to port it  to Nuxt . 
Since my forms is based on Inertia's useForm composable, and I find this package is the closest I have for Inertia's useForm, I'm trying to use it to replace my previous useForm.

While in the VILT stack, the csrf token check is not necessary to do the form request to the server , It is required for Nuxt instead (I am using my Laravel Breeze's Sanctum for the API). So my question is, is there any way to add the csrf token header while making the form request ? I am trying to add it manually as I have in Inertia (using `headers` option in the request), but it seems like this package doesn't implement the same option as it has on Inertia.

Pardon for any misconception, and any direction would be helpful

**Comment by Smef** [comment]
This package is really for setting up the precognition functionality in Nuxt for server-side stuff. I think there's another package that is designed for using Nuxt as a front-end to a Laravel back-end which might match your use case a little more closely.

Check out the Laravel Precognition module: https://nuxt.com/modules/laravel-precognition
